### ISSUE TITLE
CSS for AvatarList.astro breaks on empty pages but only on dev server

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#18]
To replicate:

- clone the repo at https://github.com/snowpackjs/astro-docs/commit/70a4d0cf164867f82c6e1d652bc8128ae7a400a6
- build the repo & serve it with `npx serve dist`, navigate to http://127.0.0.1:5000/basic-concepts/layouts
- compare to `yarn start` and http://127.0.0.1:3000/basic-concepts/layouts (or https://astro-docs-preview.vercel.app/basic-concepts/layouts)

http://127.0.0.1:3000/basic-concepts/layouts:

<img width="923" alt="list of images in normal top down order" src="https://user-images.githubusercontent.com/10626596/122988513-6f759080-d367-11eb-9626-36aed0981d72.png">

This should look like the normal `AvatarList.astro`.

<img width="777" alt="list of images in the expected, left to right order, with an overlap to be fancy" src="https://user-images.githubusercontent.com/10626596/122988589-87e5ab00-d367-11eb-8aef-025bd51f924d.png">

**Comment by jasikpark** [comment]
Unless I'm somehow adding a bug in #17?

<img width="789" alt="image" src="https://user-images.githubusercontent.com/10626596/122988904-dabf6280-d367-11eb-830b-0ba5a2099205.png">

**Comment by jasikpark** [comment]
Nope, it looks like it might be a bug in the dev server, since running `yarn build` locally builds the component with the correct CSS..

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
