### ISSUE TITLE
Explanation for frontmatter

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro-docs#22]
It seems that a lot of users that never worked with frontmatter or related technologies are trying to manipulate the DOM inside frontmatter, so we should have it detailed that DOM manipulation is not possible within frontmatter because it runs on the server, at build time, and not on the client/browser.

**Comment by aFuzzyBear** [comment]
Hell yes, I am actually going to go and learn more about frontmatter and textmate just to get a bit versed in this _Astro tech_

**Comment by itskitto** [comment]
Good point y'all, I'll take a look as well and see what I can source

**Comment by aFuzzyBear** [comment]
I honestly do think, ince we write up on the frontmatter, we might just hit the seo roof and get most of the traffic, cause there is actually not much of coherent, structured, content out there, this pushes the convo out further, when Fred was talking in the RFC 22/06, about the possibility of having an open standard for markdown component files for astro, and potentially something wider, I totally see what he means by it, there is nothing really out there, apart from use frontmatter with Yaml and Toml, Jekyll and a few other parsing repos that kinda explains what's it all about,

**Comment by ewatch** [comment]
@aFuzzyBear Did research myself as well and agree to your last comment and will propose some content for the documentation. We can also see if we can contribute together maybe.

**Comment by aFuzzyBear** [comment]
@ewatch that would be amazing bud, Ill pull some stuff together and find a spare gdoc to stick it in, and we can see what we can do with it from there, =)

**Comment by itskitto** [comment]
> I honestly do think, ince we write up on the frontmatter, we might just hit the seo roof and get most of the traffic, cause there is actually not much of coherent, structured, content out there, this pushes the convo out further, when Fred was talking in the RFC 22/06, about the possibility of having an open standard for markdown component files for astro, and potentially something wider, I totally see what he means by it, there is nothing really out there, apart from use frontmatter with Yaml and Toml, Jekyll and a few other parsing repos that kinda explains what's it all about,

Ooo, I love this. let's super optimize that page and see what happens!

**Comment by FredKSchott** [comment]
Makes sense to me to take some time to explain what you can and can't do in the component frontmatter. I think even just having a really clear .astro example with docs would help users. Something like

```
---
// Welcome to your first Astro Component!
// you can use the frontmatter to write JavaScript (or TypeScript!) that will run during the build.
// Note: this code never gets sent to the browser, so you don't have access to the DOM.
// A console.log, for example, will run in the CLI during your build.
// You do, however, have the ability to reference any variables in your template.
const foo = 42;
---
<div>My favorite number is {foo}</div>
```

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
