### ISSUE TITLE
Could we setup something like @renovatebot to stay up-to-date w/ astro?

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#24]
https://docs.renovatebot.com/install-github-app/

It's probably helpful for us to stay in step w/ the latest astro so that we're running into the same questions and breaking changes anyone else might have:

If we setup @renovatebot or @dependabot to make automated update PR's, then we can have vercel build those PR's as a test to see at least whether there's any problems with it!

**Comment by itskitto** [comment]
Yes! We definitely need this, I've never setup either of these before. Is this something that the core team will need to setup or can we accomplish this ourselves?

**Comment by jasikpark** [comment]
Someone with admin access to the repo will have to allow the Github App, but I'll make a PR to add a renovatebot config!

**Comment by jasikpark** [comment]
cc @FredKSchott

**Comment by FredKSchott** [comment]
Works for me! I've had trouble with these in larger projects so I'm not necessarily +1 on adding to the main astro repo, but this use-case of "must stay up to date with astro!" makes a lot of sense.

**Comment by FredKSchott** [comment]
Added https://github.com/snowpackjs/astro-docs/blob/main/.github/dependabot.yml to the repo

**Comment by jasikpark** [comment]
:0 wait I thought we were going with `yarn` not `npm` or does dependabot not care

**Comment by FredKSchott** [comment]
I think it can do both! confirming now in https://github.com/snowpackjs/astro-docs/pull/30
