### ISSUE TITLE
Show off Astro sites!

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#27]
~~It would be pretty cool if we could some how make a Netflix style slider that shows off all of the example sites!~~

~~- slider, not a carousel: https://lsnrae.medium.com/if-you-must-use-a-carousel-make-it-accessible-977afd0173f4~~

~~![image](~~https://user-images.githubusercontent.com/10626596/123173035-9a351700-d443-11eb-96a7-a5a52e13d4de.png~~)~~

cc the non-existent @snowpackjs/maintainers/design role xD 

It sounds like a carousel is less popular, but there's another design to copy from in: https://nextjs.org/showcase

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/10626596/123319328-e2ad0d00-d4f5-11eb-89a9-6c60a899fd0e.png">

Possible showcase sites include:
- https://navillus.dev/
- https://backlight.dev
- https://divriots.com

**Comment by aFuzzyBear** [comment]
Gonna need a lot of Astro sites to fill this awesome idea up,

**Comment by Hanawa02** [comment]
@natemoo-re was the Designer for the core Team

**Comment by Hanawa02** [comment]
I will also add here some links from the discord channel that we could show off:

- https://trusting-roentgen-7624ba.netlify.app/ (from Chris Bongers)

**Comment by starchildluke** [comment]
Happy to volunteer mine: https://lukealexdavis.co.uk/

**Comment by rebelchris** [comment]
This would rather sit on the website not?
VS in the docs? However a reference would be a good point.

Another example is eleventy rendering the showcases directly (runtime)
https://www.11ty.dev/#built-with-eleventy

**Comment by Hanawa02** [comment]
Our docs will be part of the Website, if I'm not mistaken.

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
