### ISSUE TITLE
Add Third party links to Renderers Page

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro-docs#35]
Links should be added to this issue for now, and Later on (when doing the renderers page) we add the third party renderers section.

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
