### ISSUE TITLE
Add `node-fetch` note for querying APIs

### ISSUE THREAD

**Issue by cassidoo** [snowpackjs/astro-docs#37]
When you query an API outside of a `.astro` component, you need to use `node-fetch`, which should be documented for folks creating utility functions.

**Comment by natemoo-re** [comment]
We should definitely document this, at least until [`astro#410`](https://github.com/snowpackjs/astro/issues/410) is resolved.

**Comment by kolodziejczak-sz** [comment]
in the meantime I came up with this temporary solution:

```javascript
// astro.config.mjs
import fetch from 'node-fetch';

export default {
    renderers: ['@astrojs/renderer-preact'],
    injectGlobals: (() => {
        globalThis.fetch = fetch;
    })(), //IIFE, the name of the fn is not important but it should not collide with any supported config property
};
```

**Comment by jasikpark** [comment]
I added a blurb to the end of `/guides/data-fetching.md` that hopefully fulfills that. Let me know if y'all think the little hack for adding global fetch @kolodziejczak-sz came up with should be added - I think it should just be available in this issue 🤔
