### ISSUE TITLE
add this project url (astro documenation) to astro repo readme.md

### ISSUE THREAD

**Issue by yeukfei02** [snowpackjs/astro-docs#48]
Hi all,

I find this is a nice framework compare to react and svelte, can someone or do I submit a pull request to add astro docs link to `astro` repo readme.md?

or someone will do this?

Thanks.

**Comment by yeukfei02** [comment]
I submitted my pull request in here:

https://github.com/snowpackjs/astro/pull/616

**Comment by FredKSchott** [comment]
Thanks for filing! lets follow up in that PR!

**Comment by FredKSchott** [comment]
fyi we're getting this docs site ready to release this week, so it shouldn't be long now before its publicly linked. In the meantime, the `docs/` dir should have all of the same content.
