### ISSUE TITLE
Pages for Group `Start Here`

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro-docs#6]
Task  -> Assignee
- [x] Installation -> @aFuzzyBear
- [x] Quickstart -> @jgil-r 
- [x] Examples -> @FredKSchott

**Comment by jgil-r** [comment]
I can start working on Quickstart

**Comment by FredKSchott** [comment]
I got rid of "what is Astro" for now, that can be one of the last pages that we add back in once the main docs/reference is done

I'll tackle "Examples" and we can get our first section issue closed!
