### ISSUE TITLE
Wrong sidebar hover state colors

### ISSUE THREAD

**Issue by jgil-r** [snowpackjs/astro-docs#60]
The hover state colors in sidebar menu for dark theme seems to be using the same color that is being used for light theme. 

![astro-docs-menu-hover](https://user-images.githubusercontent.com/59382692/125342289-533b9280-e31a-11eb-8fac-e3bedd1ac105.png)

**Comment by jasikpark** [comment]
That was introduced here: https://github.com/snowpackjs/astro-docs/commit/372d20db7f3b5c09ba8b6f06b625fc7b8e195bd5#r53379131

**Comment by FredKSchott** [comment]
This was me! I've been moving pretty quick as I try to get the site ready for everyone to review this week. 

I think I introduced this in a rush, because there wasn't a themed color for this low-opacity accent. There probably should be one!

**Comment by FredKSchott** [comment]
@natemoo-re I'm really feeling the limits of CSS variables this week, specifically in wanting to customize the opacity/strength of a variable'd color. Any ideas / tips besides just creating a variable for every color you might want?

**Comment by jgil-r** [comment]
> This was me! I've been moving pretty quick as I try to get the site ready for everyone to review this week. 
> 
> 
> 
> I think I introduced this in a rush, because there wasn't a themed color for this low-opacity accent. There probably should be one!

I see. Let me know if I can help finish up anything. I know you mentioned you were trying to get a lot of this done by end of week.

**Comment by jgil-r** [comment]
Regarding CSS variables. Would transitioning from hex to hsla be a better option? I think it might make it easier to have a base set of colors, and be able to dynamically change the opacity value.

**Comment by jasikpark** [comment]
I've got a fix in #61, a good rework of the theme / css variables might be as @jgil-r is suggesting: https://blog.maximeheckel.com/posts/the-power-of-composition-with-css-variables/

I think following the css variable composition in this blog post would work best for us!
