### ISSUE TITLE
Make `node-fetch` example actually work by using pokeapi

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#79]
Update the example in /pages/guides/data-fetching.md to use the pokeapi like @FredKSchott suggested in #66

**Comment by jasikpark** [comment]
Also need to update that in https://astro-docs-preview.vercel.app/core-concepts/astro-pages

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
