### ISSUE TITLE
Add side-by-side component for showing off code

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#80]
It'd be great to make a component that styles a code example and the rendered component side-by-side! 

Could honestly just look like hooking up Prism and a little css grid box that renders the source on the right side 🤔 though i'm not sure how you say "create a component out of this source code that was passed to me as a prop", though maybe we do like the astro tests and pull from a code examples folder 🤔 

```tsx
<CodeExample src="src/examples/fetchingdata.tsx" />
```

This reads to me as linked to the issue in the astro repo about wanting a compiler api though!

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
