### ISSUE TITLE
SiteSidebar focus styles are clipped by overflow.

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro-docs#83]
![image](https://user-images.githubusercontent.com/10626596/125697555-ea441312-0bbb-4aa0-80a5-ef2924489c09.png)
![image](https://user-images.githubusercontent.com/10626596/125697559-82d62230-2432-47b6-b9c4-8875d3dafe92.png)

reported by @okikio#3174 on discord https://discord.com/channels/830184174198718474/853350631389265940/864984473699221514

Maybe it would make sense to use something like [tailwind focus rings](https://tailwindcss.com/docs/ring-width) to avoid it?

cc: @okikio

**Comment by okikio** [comment]
I'm planning to use Tailwind for that. I did the same thing on josephojo.com and on bundle.js.org

**Comment by jasikpark** [comment]
I would say just copy over the rules, don't actually pull in a tailwind config, yeah?

**Comment by okikio** [comment]
Yeah, ok

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.

**Comment by okikio** [comment]
Did you fix the bugs in `astro-docs`?
