### ISSUE TITLE
ASCII Replacing { Character

### ISSUE THREAD

**Issue by joshuaferr1s** [snowpackjs/astro-docs#84]
I noticed across the site `{` is being replaced by `&#123;`. But not in every instance.

E.g. 1: Collections page: `const &#123; collection } = Astro.props;`

**Comment by jasikpark** [comment]
This seems to be something fun with how Astro decides to escape those opening brackets...

**Comment by FredKSchott** [comment]
FYI: the docs have been successfully merged back into the main Astro repo: https://github.com/snowpackjs/astro/tree/main/docs

This issue will be migrated over soon, but if anyone can take a look at this issue before then, please remember to create a PR against the main astro repo instead.
